steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
    dir: 'functions/autodeploy'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    dir: 'functions/autodeploy'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'cf-github-test', '--region=US/Central --trigger-topic', '--runtime', 'nodejs10', '--entry-point', 'helloWorld']
    dir: 'functions/autodeploy'