steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cf-github-test
      - --source=./first
      - --trigger-topic=custom-match-trigger
      - --runtime=nodejs8
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cf-github-test-2
      - --source=./second
      - --trigger-topic=cf-custom-match-trigger
      - --runtime=nodejs8
